//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldCupForm.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WorldCupForm.Properties.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearances:.
        /// </summary>
        internal static string Appearances_ {
            get {
                return ResourceManager.GetString("Appearances:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Away:.
        /// </summary>
        internal static string Away_ {
            get {
                return ResourceManager.GetString("Away:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Access Mode.
        /// </summary>
        internal static string DataAccessMode {
            get {
                return ResourceManager.GetString("DataAccessMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Loaded.
        /// </summary>
        internal static string DataLoaded {
            get {
                return ResourceManager.GetString("DataLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favourite Players.
        /// </summary>
        internal static string FavouritePlayers {
            get {
                return ResourceManager.GetString("FavouritePlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favourite Team.
        /// </summary>
        internal static string FavouriteTeam {
            get {
                return ResourceManager.GetString("FavouriteTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        internal static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goals:.
        /// </summary>
        internal static string Goals_ {
            get {
                return ResourceManager.GetString("Goals:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home:.
        /// </summary>
        internal static string Home_ {
            get {
                return ResourceManager.GetString("Home:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Data....
        /// </summary>
        internal static string LoadingData {
            get {
                return ResourceManager.GetString("LoadingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matches Ranking.
        /// </summary>
        internal static string MatchesRanking {
            get {
                return ResourceManager.GetString("MatchesRanking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MEN.
        /// </summary>
        internal static string MEN {
            get {
                return ResourceManager.GetString("MEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players.
        /// </summary>
        internal static string Players {
            get {
                return ResourceManager.GetString("Players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players Ranking.
        /// </summary>
        internal static string PlayersRanking {
            get {
                return ResourceManager.GetString("PlayersRanking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Matches.
        /// </summary>
        internal static string PrintMatches {
            get {
                return ResourceManager.GetString("PrintMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Players.
        /// </summary>
        internal static string PrintPlayers {
            get {
                return ResourceManager.GetString("PrintPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranking Lists.
        /// </summary>
        internal static string RankingLists {
            get {
                return ResourceManager.GetString("RankingLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Team.
        /// </summary>
        internal static string SelectTeam {
            get {
                return ResourceManager.GetString("SelectTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Team as Favourite.
        /// </summary>
        internal static string SetTeamAsFav {
            get {
                return ResourceManager.GetString("SetTeamAsFav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visitors:.
        /// </summary>
        internal static string Visitors_ {
            get {
                return ResourceManager.GetString("Visitors:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WOMEN.
        /// </summary>
        internal static string WOMEN {
            get {
                return ResourceManager.GetString("WOMEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow Cards:.
        /// </summary>
        internal static string YellowCards_ {
            get {
                return ResourceManager.GetString("YellowCards:", resourceCulture);
            }
        }
    }
}
