//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldCupWPF.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WorldCupWPF.Properties.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captain:.
        /// </summary>
        public static string Captain_ {
            get {
                return ResourceManager.GetString("Captain:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Access Mode.
        /// </summary>
        public static string DataAccessMode {
            get {
                return ResourceManager.GetString("DataAccessMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Loaded!.
        /// </summary>
        public static string DataLoaded {
            get {
                return ResourceManager.GetString("DataLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Loading....
        /// </summary>
        public static string DataLoading {
            get {
                return ResourceManager.GetString("DataLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draws:.
        /// </summary>
        public static string Draws_ {
            get {
                return ResourceManager.GetString("Draws:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIFA Code:.
        /// </summary>
        public static string FIFACode_ {
            get {
                return ResourceManager.GetString("FIFACode:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games:.
        /// </summary>
        public static string Games_ {
            get {
                return ResourceManager.GetString("Games:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal Difference:.
        /// </summary>
        public static string GoalDifference_ {
            get {
                return ResourceManager.GetString("GoalDifference:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goals:.
        /// </summary>
        public static string Goals_ {
            get {
                return ResourceManager.GetString("Goals:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goals Recieved:.
        /// </summary>
        public static string GoalsRecieved_ {
            get {
                return ResourceManager.GetString("GoalsRecieved:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goals Scored:.
        /// </summary>
        public static string GoalsScored_ {
            get {
                return ResourceManager.GetString("GoalsScored:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Losses:.
        /// </summary>
        public static string Losses_ {
            get {
                return ResourceManager.GetString("Losses:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string Name_ {
            get {
                return ResourceManager.GetString("Name:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National Team Name:.
        /// </summary>
        public static string NationalTeamName_ {
            get {
                return ResourceManager.GetString("NationalTeamName:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number:.
        /// </summary>
        public static string Number_ {
            get {
                return ResourceManager.GetString("Number:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position:.
        /// </summary>
        public static string Position_ {
            get {
                return ResourceManager.GetString("Position:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window Mode:.
        /// </summary>
        public static string WindowMode {
            get {
                return ResourceManager.GetString("WindowMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wins:.
        /// </summary>
        public static string Wins_ {
            get {
                return ResourceManager.GetString("Wins:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YellowCards:.
        /// </summary>
        public static string YellowCards_ {
            get {
                return ResourceManager.GetString("YellowCards:", resourceCulture);
            }
        }
    }
}
